server {
    listen 80;

    # 1. Phục vụ Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Quan trọng cho React Router
    }

    # 2. Reverse Proxy gọi API sang Backend (Flask)
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}